import { ethers } from "ethers";
import hre from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

async function main() {
  // In Hardhat v3 with hardhat-toolbox-mocha-ethers, access ethers via the plugin
  const hreAny = hre as any;
  const hEthers = hreAny.ethers;

  const [deployer] = await hEthers.getSigners();
  const deployerBal = await hEthers.provider.getBalance(deployer.address);
  console.log("Deploying with account:", deployer.address);
  console.log("Balance:", ethers.formatEther(deployerBal), "ETH\n");

  // 1. Deploy MockUSDT
  console.log("Deploying MockUSDT...");
  const mockUSDT = await hEthers.deployContract("MockUSDT");
  await mockUSDT.waitForDeployment();
  const usdtAddress = await mockUSDT.getAddress();
  console.log("MockUSDT deployed to:", usdtAddress);

  // 2. Deploy TrustFlow
  console.log("Deploying TrustFlow...");
  const trustflow = await hEthers.deployContract("TrustFlow", [usdtAddress]);
  await trustflow.waitForDeployment();
  const trustflowAddress = await trustflow.getAddress();
  console.log("TrustFlow deployed to:", trustflowAddress);

  // 3. Mint USDT to the first 5 test accounts for demo
  const signers = await hEthers.getSigners();
  const mintAmount = ethers.parseUnits("10000", 6);
  for (let i = 1; i < Math.min(5, signers.length); i++) {
    await mockUSDT.transfer(signers[i].address, mintAmount);
    console.log(`  Sent 10,000 USDT to ${signers[i].address}`);
  }

  // 4. Write config.js for the frontend
  const frontendDir = path.join(__dirname, "../frontend");
  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  const networkName = (hre as any).network?.name ?? "localhost";
  const configContent = `// Auto-generated by deploy.ts\nwindow.DEPLOY_CONFIG = {\n  TrustFlow: "${trustflowAddress}",\n  MockUSDT:  "${usdtAddress}",\n  network:   "${networkName}",\n  chainId:   31337\n};\n`;

  fs.writeFileSync(path.join(frontendDir, "config.js"), configContent);

  console.log("\n─────────────────────────────");
  console.log("  TrustFlow :", trustflowAddress);
  console.log("  MockUSDT  :", usdtAddress);
  console.log("─────────────────────────────");
  console.log("\nFrontend config written to frontend/config.js");
  console.log("Open frontend/index.html in your browser (MetaMask on localhost:8545, chainId 31337)");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
